### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by odonyde** [Jason3S/hunspell-reader#1]
Thanks for the Code Spellchecker extension and the option to add own dictionaries! Unfortunately it didn't work in my case: I tried to generate a word list from a Brazilian Portuguese hunspell dictionary (pt_BR.dic has 4.474 KB, pt_BR.aff has 949 KB) but after about 30 minutes hunspell-reader runs into a "JavaScript heap out of memory" error (node v6.9.2):

hunspell-reader words ./hunspell/pt_BR.dic -o ./raw-dictionaries/wordsPtBr.txt
Write words
Sort: No
Unique: No
Ignore Case: No
Dic file: ./hunspell/pt_BR.dic
Aff file: ./hunspell/pt_BR.aff
Generating Words

<--- Last few GCs --->

 1733379 ms: Mark-sweep 1371.9 (1434.1) -> 1371.8 (1434.1) MB, 3985.0 / 0.0 ms [allocation failure] [GC in old space requested].
 1737379 ms: Mark-sweep 1371.8 (1434.1) -> 1371.8 (1434.1) MB, 4000.0 / 0.0 ms [allocation failure] [GC in old space requested].
 1741379 ms: Mark-sweep 1371.8 (1434.1) -> 1371.7 (1403.1) MB, 4000.0 / 0.0 ms [last resort gc].
 1745426 ms: Mark-sweep 1371.7 (1403.1) -> 1371.6 (1403.1) MB, 4047.0 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003C12E5CFB61 <JS Object>
    1: InnerArrayReduce(aka InnerArrayReduce) [native array.js:~1107] [pc=000001484A66C509] (this=000003C12E504381 <undefined>,bw=000003D81F2B7429 <JS Function affixRules.map.reduce.map.reduce (SharedFunctionInfo 000002EA0E4772A1)>,aa=000003D81F2B7471 <JS Array[0]>,w=000002DD5560D5E9 <JS Array[452]>,x=452,bv=2)
    2: reduce [native array.js:~1130] [pc=000001484A640373] (this=000002DD5560D5E9...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by Jason3S** [comment]
Thank you.  This one might be a bit hard to fix.  I'll take a look.

**Comment by Jason3S** [comment]
Can you tell me where you found the Portuguese Hunspell dictionary?

**Comment by odonyde** [comment]
Thanks for taking a look into this! I used the Brazilian Portuguese hunspell dictionary from the following GitHub repository: [https://github.com/titoBouzout/Dictionaries](url)

I have meanwhile also tested the word list generation with Node v6.9.5 and v7.5.0 - unfortunately with the same out-of-memory error (except that v7.5.0 took 1h50min to run into the error instead of 30min as the both tested Node 6 versions).

**Comment by Jason3S** [comment]
Thank you for the link.

I am not sure if the reader can deal with that size of a dictionary.  Looking at the output of the dictionary, it generates many millions of words.

Is it possible to use the European version of the dictionary?  That one seems to be a bit more reasonable in size.

**Comment by odonyde** [comment]
Thank you for your feedback.

Brazilian Portuguese has developed quite differently from the 'original' Portuguese and has strong influences of indigenous languages and native languages of other immigrant groups. This might be also a reason for the increased word base...

In my code base, I use primarily English (for naming and comments) and Brazilian Portuguese only for localized output (labels, messages, etc.). So I think I will go with the approach of simply using the default English spell checking and adding all required Brazilian Portuguese words to cSpell's workspace dictionary after spell checking them externally.

**Comment by Jason3S** [comment]
Maybe try using the European Portuguese as a basis, and then you only need to add the Brazilian differences.

I am able to reproduce the issue on my machine, so I will continue to look into why it runs out of memory.  It was designed to be able to work with large word sets, so something is being kept around longer than necessary.

**Comment by odonyde** [comment]
Using a European Portuguese dictionary for Brazilian Portuguese texts might unfortunately produce quite some false-positives and false-negatives. For instance, reception in European Portuguese is "receção", whereas Brazilian Portuguese adds a p to the spelling of "recepção". And such single letter spelling mistakes are quite hard to catch manually, especially as I am a non-native speaker... :-)

**Comment by Jason3S** [comment]
Got it.

I just published a new version of the reader.  It won't generate all the words, but it will output the root words.  The -T option turns off adding the prefix and suffix to each word in the dictionary.

This should at least give you 300k words to work with.

```sh
hunspell-reader words -T -s -o temp/pt.txt dictionaries/Portuguese\ \(Brazilian\).dic
```

You will need to install the version 1.0.2:

```sh
npm install -g hunspell-reader
```

**Comment by odonyde** [comment]
Awesome! Thank you! Version 1.0.2 generates the raw word list within seconds and I was also able to build and apply the dictionary.

As Hunspell's knowledge about verb conjugation, singular/plural, and augmentative/diminutive is not considered in the word list generation, about 70% of false-negatives still remain in my sample TypeScript project in comparison to not using any Portuguese dictionary. So there is still some manual work required to enhance the generated word list - but it is at least 30% less work than starting from zero. :-)

**Comment by Jason3S** [comment]
It is the transformations that add the conjugations.  But this is better than nothing.  

I am still looking into why it takes so long.  Part of it has to do with the way the .aff file was built.

**Comment by Jason3S** [comment]
This should be fixed.  If you install version 1.0.3, you can make a word list from the Portuguese.  I had found an issue with how files are written.  I'll need to fix some of the other tools as well.

The file is very large, so it means the extension will use a LOT of memory.

**Comment by odonyde** [comment]
Hi! While version 1.0.2 generated the word list without issues, version 1.0.3 runs again into the out-of-memory error:
```
hunspell-reader words ./hunspell/pt_BR.dic -o ./raw-dictionaries/wordsPtBr3.txt
Write words
Sort: No
Unique: No
Ignore Case: No
Dic file: ./hunspell/pt_BR.dic
Aff file: ./hunspell/pt_BR.aff
Generating Words

<--- Last few GCs --->

 1315608 ms: Mark-sweep 1371.0 (1434.1) -> 1370.9 (1434.1) MB, 3922.0 / 0.0 ms [allocation failure] [GC in old space requested].
 1319514 ms: Mark-sweep 1370.9 (1434.1) -> 1372.7 (1403.1) MB, 3906.0 / 0.0 ms [last resort gc].
 1323436 ms: Mark-sweep 1372.7 (1403.1) -> 1374.6 (1403.1) MB, 3922.0 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000348B5BCFB61 <JS Object>
    1: InnerArrayReduce(aka InnerArrayReduce) [native array.js:~1107] [pc=00000136CBEBC909] (this=00000348B5B04381 <undefined>,bw=000002F43AFB13A9 <JS Function affixRules.map.reduce.map.reduce (SharedFunctionInfo 0000010B5A8CBE41)>,aa=000002F43AFB13F1 <JS Array[0]>,w=000001FA32810201 <JS Array[549]>,x=549,bv=2)
    2: reduce [native array.js:~1130] [pc=00000136CBE7C233] (this=000001FA32810201...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by Jason3S** [comment]
Let me check.

**Comment by Jason3S** [comment]
It just ran fine for me.  It took about 2 minutes.  I use the word list from Github: https://github.com/titoBouzout/Dictionaries

I am running Node 7.5.  Do you have an SSD or HDD?

**Comment by odonyde** [comment]
Win 10, 8 GB RAM, SSD, Node 6.9.5 (latest LTS version). I'll try it again in a virtual machine with Node 7.5.0 (latest 'Current' version)...

**Comment by Jason3S** [comment]
What happens if you don't add the -o option?

**Comment by odonyde** [comment]
Ups, my mistake: I had updated the local repository but called the outdated global version of hunspell-reader. I can confirm now that version 1.0.3 runs well with both Node 6.9.5 and 7.5.0. It generates a word list of about 150MB with slightly above 1 million entries.

Please let me know when the adaption of the other tools you mentioned is ready and I'll give it a spin... (I guess you refer to [cSpell-WordLists](https://github.com/Jason3S/cSpell-WordLists), right? It produces an out-of-memory error right now if run on this large word list generated by hunspell-reader...)

**Comment by Jason3S** [comment]
It is a lot of words.  10 million with the average length of 15 characters.

I am looking at how to reduce the size in memory.  Just to load it into memory it takes about 350MB.
Javascript uses 2 bytes per character in memory + the cost of managing the strings.

**Comment by odonyde** [comment]
I understand... Would it maybe be a viable approach to integrate the original [hunspell server](https://github.com/hunspell/hunspell) into Code Spellchecker? This way the hunspell dictionaries could be used without transpiling them into word lists. The hunspell server is written in C and seems to be quite fast even with large dictionaries and texts, but needs to be compiled for the different host systems. I once compiled it for my Win 10 system and created step-by-step instructions for the compilation process. If you are interested I can publish them.

The hunspell server for sure does not know anything about the camelCase concept and even less about integrating with VS Code. This is where your magic comes in! :-) You could maybe apply your rules and filters on the text to be validated and send the pre-processed text to a local hunspell instance for spell-checking against it's dictionaries.

**Comment by Jason3S** [comment]
Hunspell is very slow.  It is not designed for speed.  It is designed to make it easy to write word lists.

This extension uses Hunspell: https://marketplace.visualstudio.com/items?itemName=swyphcosmo.spellchecker

It is very slow.  Many seconds to check a document.  See his comments about performance.

cSpell will check a document as fast as you can type.

**Comment by odonyde** [comment]
I see. I took a look at the generated word list and as a first step to try to reduce it's size, I would suggest to treat all succeeding object pronouns as separate words. For instance, 'azurziste-se-lhes' would become 'azurziste' (the conjugated verb) + 'se' (not necessary to add to word list as < 3 chars) + 'lhes'. As those object pronouns are repeated for each verb, this step should reduce the file size significantly.

Maybe it could even be a good general approach to treat hyphen-joined word components as separate words during spell checking, analogous to your camelCase concept. What do you think?
